name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # runs daily at midnight UTC
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: ""
          plugin_isocalendar: yes
